name: push

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "README.md"
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - name: Test
        run: |
          nix develop --command go test -coverprofile=c.out -v ./...
          nix develop --command go tool cover -func=c.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - name: golangci-lint
        run: nix develop --command golangci-lint run --timeout 2m ./...
